// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBBuyKvPGujNFe-kmM99t7Fhz97yOs9xY',
    appId: '1:846637718415:web:8a1850fc21e20953d949fa',
    messagingSenderId: '846637718415',
    projectId: 'food-donation-app-abf24',
    authDomain: 'food-donation-app-abf24.firebaseapp.com',
    storageBucket: 'food-donation-app-abf24.appspot.com',
    measurementId: 'G-Y28MBD7L81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiRSHKJPn0xDl2ZMgIEfwVkiolzrAM9WI',
    appId: '1:846637718415:android:c80074881aea7647d949fa',
    messagingSenderId: '846637718415',
    projectId: 'food-donation-app-abf24',
    storageBucket: 'food-donation-app-abf24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6pyKS2OEkZEjHLIdIVWeLd14n0cGDnD8',
    appId: '1:846637718415:ios:4496af89761cdd9fd949fa',
    messagingSenderId: '846637718415',
    projectId: 'food-donation-app-abf24',
    storageBucket: 'food-donation-app-abf24.appspot.com',
    iosBundleId: 'com.example.foodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6pyKS2OEkZEjHLIdIVWeLd14n0cGDnD8',
    appId: '1:846637718415:ios:8946e5f4f73ec28ad949fa',
    messagingSenderId: '846637718415',
    projectId: 'food-donation-app-abf24',
    storageBucket: 'food-donation-app-abf24.appspot.com',
    iosBundleId: 'com.example.foodDonationApp.RunnerTests',
  );
}
